# Generated by Django 5.0.6 on 2024-06-30 01:49

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('feedback', 'Feedback'), ('recognition', 'Recognition'), ('grievance', 'Grievance')], default='feedback', max_length=20),
        ),
        migrations.AlterField(
            model_name='workaddress',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='default-slug', editable=False, populate_from='address', unique=True),
            preserve_default=False,
        ),
    ]
